version: '3'
services:
    mssql:
      image: microsoft/mssql-server-linux:latest
      container_name: mssql-server
      ports:
        - 1433:1433
      volumes:
        - "~/AdventureWorks-oltp-install-script:/work"
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssw0rd!
